package com.example.pixdate.ui.screens.folders

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.pixdate.data.local.entity.FolderEntity
import com.example.pixdate.data.repository.PixDateRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import com.example.pixdate.data.local.entity.PhotoEntity

class FoldersViewModel(
    private val repository: PixDateRepository
) : ViewModel() {

    companion object {
        private const val TAG = "PIXDATE_FOLDERS"
        private const val SUBSCRIPTION_TIMEOUT_MS = 5_000L
    }

    /**
     * Lista reactiva de carpetas.
     */
    val folders: StateFlow<List<FolderEntity>> = repository.getAllFoldersFlow()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(SUBSCRIPTION_TIMEOUT_MS),
            initialValue = emptyList()
        )

    /**
     * Mapa de fotos agrupadas por ID de carpeta (Optimizado en el ViewModel).
     */
    val photosByFolderId: StateFlow<Map<Long, List<PhotoEntity>>> = repository.getAllPhotos()
        .map { photos ->
            photos
                .filter { it.folderId != null }
                .groupBy { it.folderId!! }
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(SUBSCRIPTION_TIMEOUT_MS),
            initialValue = emptyMap()
        )

    /**
     * Crea una carpeta manual.
     */
    fun createFolder(
        name: String,
        description: String = ""
    ) {
        viewModelScope.launch {
            val trimmedName = name.trim()
            val trimmedDescription = description.trim()

            if (trimmedName.isEmpty()) {
                return@launch
            }

            try {
                withContext(Dispatchers.IO) {
                    val existingFolder = repository.getFolderByName(trimmedName)

                    if (existingFolder != null) {
                        Log.d(TAG, "No se crea carpeta: ya existe \"$trimmedName\"")
                        return@withContext
                    }

                    val now = System.currentTimeMillis()

                    val folder = FolderEntity(
                        name = trimmedName,
                        description = trimmedDescription.takeIf { it.isNotEmpty() },
                        isAutoGenerated = false,
                        createdAt = now
                    )

                    val folderId = repository.insertFolder(folder)

                    Log.d(TAG, "Carpeta creada: id=$folderId, name=\"$trimmedName\"")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error creando carpeta \"$trimmedName\": ${e.message}", e)
            }
        }
    }

    /**
     * Renombra una carpeta.
     */
    fun renameFolder(
        folder: FolderEntity,
        newName: String
    ) {
        viewModelScope.launch {
            val trimmedName = newName.trim()

            if (trimmedName.isEmpty() || trimmedName == folder.name) {
                return@launch
            }

            try {
                withContext(Dispatchers.IO) {
                    val existingFolder = repository.getFolderByName(trimmedName)

                    if (
                        existingFolder != null &&
                        existingFolder.folderId != folder.folderId
                    ) {
                        Log.d(
                            TAG,
                            "No se renombra carpeta ${folder.folderId}: \"$trimmedName\" ya existe"
                        )
                        return@withContext
                    }

                    val updatedFolder = folder.copy(
                        name = trimmedName
                    )

                    repository.updateFolder(updatedFolder)

                    Log.d(
                        TAG,
                        "Carpeta renombrada: id=${folder.folderId}, \"${folder.name}\" -> \"$trimmedName\""
                    )
                }
            } catch (e: Exception) {
                Log.e(
                    TAG,
                    "Error renombrando carpeta ${folder.folderId} a \"$trimmedName\": ${e.message}",
                    e
                )
            }
        }
    }

    /**
     * Elimina una carpeta.
     *
     * Importante: Este método solo borra la carpeta de la base de datos local.
     * Las fotos asociadas perderán su referencia a la carpeta (folderId = null) 
     * mediante la estrategia de OnConflict o actualización previa. No se borran
     * del dispositivo.
     */
    fun deleteFolder(folder: FolderEntity) {
        viewModelScope.launch {
            try {
                withContext(Dispatchers.IO) {
                    repository.deleteFolder(folder)
                }

                Log.d(TAG, "Carpeta eliminada: id=${folder.folderId}, name=\"${folder.name}\"")
            } catch (e: Exception) {
                Log.e(
                    TAG,
                    "Error eliminando carpeta ${folder.folderId}: ${e.message}",
                    e
                )
            }
        }
    }

    /**
     * Limpia todas las carpetas que no tengan fotos asociadas.
     */
    fun cleanupEmptyFolders() {
        viewModelScope.launch {
            try {
                withContext(Dispatchers.IO) {
                    repository.deleteEmptyFolders()
                }
                Log.d(TAG, "Limpieza de carpetas vacías completada")
            } catch (e: Exception) {
                Log.e(TAG, "Error limpiando carpetas vacías: ${e.message}", e)
            }
        }
    }
}

class FoldersViewModelFactory(
    private val repository: PixDateRepository
) : ViewModelProvider.Factory {

    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(
        modelClass: Class<T>
    ): T {
        if (modelClass.isAssignableFrom(FoldersViewModel::class.java)) {
            return FoldersViewModel(repository) as T
        }

        throw IllegalArgumentException("Unknown ViewModel class: ${modelClass.name}")
    }
}