package com.example.pixdate.ui.screens.gallery

import android.content.Context
import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.pixdate.data.local.CsvDataSource
import com.example.pixdate.data.local.entity.FolderEntity
import com.example.pixdate.data.local.entity.PhotoAnalysisEntity
import com.example.pixdate.data.local.entity.PhotoEntity
import com.example.pixdate.data.local.entity.TagEntity
import com.example.pixdate.data.repository.PixDateRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

/**
 * Contiene toda la información relacionada con una foto en la BD.
 */
data class PhotoDetailInfo(
    val photo: PhotoEntity,
    val analysis: PhotoAnalysisEntity?,
    val folder: FolderEntity?,
    val tags: List<TagEntity>
)

class GalleryViewModel(
    private val repository: PixDateRepository
) : ViewModel() {

    // ── Estado reactivo de fotos (lectura completa) ──────────────

    val photos: StateFlow<List<PhotoEntity>> =
        repository.getAllPhotosFlow()
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.WhileSubscribed(5000),
                initialValue = emptyList()
            )

    // ── Detalle de foto seleccionada ─────────────────────────────

    private val _selectedPhotoDetail = MutableStateFlow<PhotoDetailInfo?>(null)
    val selectedPhotoDetail: StateFlow<PhotoDetailInfo?> = _selectedPhotoDetail.asStateFlow()

    /**
     * Carga toda la información relacionada con una foto desde Room:
     * - PhotoEntity (la propia foto)
     * - PhotoAnalysisEntity (descripción, categoría, modelo…)
     * - FolderEntity (carpeta a la que pertenece)
     * - List<TagEntity> (etiquetas asociadas via cross-ref)
     */
    fun loadPhotoDetail(photo: PhotoEntity) {
        viewModelScope.launch {
            val analysis = repository.getAnalysisByPhotoId(photo.photoId)
            val folder = photo.folderId?.let { repository.getFolderById(it) }
            val tags = repository.getTagsByPhotoId(photo.photoId)

            val detail = PhotoDetailInfo(
                photo = photo,
                analysis = analysis,
                folder = folder,
                tags = tags
            )

            _selectedPhotoDetail.value = detail

            // También logear todo en Logcat
            Log.d("PIXDATE_DB_UI", "═══════════════════════════════════════════════")
            Log.d("PIXDATE_DB_UI", "FOTO: $photo")
            Log.d("PIXDATE_DB_UI", "ANÁLISIS: $analysis")
            Log.d("PIXDATE_DB_UI", "CARPETA: $folder")
            Log.d("PIXDATE_DB_UI", "TAGS: ${tags.map { it.name }}")
            Log.d("PIXDATE_DB_UI", "═══════════════════════════════════════════════")
        }
    }

    fun clearPhotoDetail() {
        _selectedPhotoDetail.value = null
    }

    // ── Auto-importar CSV al iniciar si la BD está vacía ─────────

    fun autoImportIfEmpty(context: Context) {
        viewModelScope.launch {
            try {
                val count = repository.getPhotoCount()
                if (count > 0) {
                    Log.d("PIXDATE_CSV", "BD ya tiene $count fotos, no se reimporta")
                    return@launch
                }

                Log.d("PIXDATE_CSV", "BD vacía, importando CSV automáticamente...")
                val csvDataSource = CsvDataSource()
                val rows = csvDataSource.readCsvFromAssets(context)

                if (rows.isNotEmpty()) {
                    val inserted = repository.importFromCsv(rows)
                    Log.d("PIXDATE_CSV", "Auto-importación completada: $inserted fotos")
                }
            } catch (e: Exception) {
                Log.e("PIXDATE_CSV", "Error en auto-importación: ${e.message}", e)
            }
        }
    }

    // ── Insertar ejemplo manual (botón temporal +) ───────────────

    fun insertSamplePhoto() {
        viewModelScope.launch {
            val now = System.currentTimeMillis()

            val folderId = repository.insertFolder(
                FolderEntity(
                    name = "ANIMALS_$now",
                    description = "Carpeta generada para prueba",
                    isAutoGenerated = true,
                    createdAt = now
                )
            )

            val photoId = repository.insertPhoto(
                PhotoEntity(
                    contentUri = "file:///android_asset/sample_images/3354474353_daf9e168cf.jpg",
                    dateTaken = now,
                    displayName = "3354474353_daf9e168cf.jpg",
                    mimeType = "image/jpeg",
                    isProcessed = true,
                    folderId = folderId,
                    createdAt = now,
                    updatedAt = now
                )
            )

            repository.insertAnalysis(
                PhotoAnalysisEntity(
                    photoId = photoId,
                    description = "Two dogs walk in the snow, the larger dog has a fish in his mouth.",
                    mainCategory = "ANIMALS",
                    modelUsed = "Salesforce/blip-image-captioning-base",
                    processedAt = now,
                    confidence = 0.91f,
                    errorMessage = null
                )
            )

            Log.d("PIXDATE_DB", "Ejemplo insertado: photoId=$photoId, folderId=$folderId")
        }
    }

    fun markAsNotProcessed(photoId: Long) {
        viewModelScope.launch {
            repository.updateProcessedStatus(photoId, false)
        }
    }
}

class GalleryViewModelFactory(
    private val repository: PixDateRepository
) : ViewModelProvider.Factory {
    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        return GalleryViewModel(repository) as T
    }
}