package com.example.pixdate.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "folders",
    indices = [Index(value = ["name"], unique = true)]
)
data class FolderEntity(
    @PrimaryKey(autoGenerate = true)
    val folderId: Long = 0,

    val name: String,
    val description: String? = null,
    val isAutoGenerated: Boolean = true,
    val createdAt: Long
)
